name: Build and test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [8.12, 10.x, 13.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and build
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: test
        run: yarn test
        env:
          CI: true
